name: "Deploy Backend to Azure"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Build
        run: dotnet build --nologo --configuration Release src/api/api.csproj

      - name: Publish
        run: dotnet publish --no-build --configuration Release src/api/api.csproj -o src/_publish_api

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hammerhackamole-api"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: src/_publish_api
